#ceURI=https://w2019p8.lab.grupolpa.com:9443/wsi/FNCEWS40MTOM/
ceURI=http://172.16.16.113:9080/wsi/FNCEWS40MTOM/
# ceURI=https://p8-55biogenesis.bago.lpa.dev:9443/wsi/FNCEWS40MTOM/
# ceURI=http://p855-cargill.lab.grupolpa.com:9080/wsi/FNCEWS40MTOM/	
userName=p85ceadmin
# userName=p8ceadmin
password=Filenet01
# password=Admin123
#objectStore=OS1_FVG
# objectStore=TEST
#objectStore=objst1
# objectStore=OBJST2
objectStore=TESTING
#objectStore=Soporte
# objectStore=ICM_T
# objectStore=ICM_D
documentSearch=Select * FROM Document where Id IS NOT NULL
folderSearch=Select * FROM Folder where Id IS NOT NULL
customObjectSearch=Select * FROM CustomObject where Id IS NOT NULL
classSearch=Select * FROM ClassDefinition where Id IS NOT NULL
annotationSearch=Select * FROM Annotation where Id IS NOT NULL
choiceListSearch=Select * FROM ChoiceList where Id IS NOT NULL
eventSearch=Select * FROM Event where Id IS NOT NULL
storagePolicySearch=Select * FROM StoragePolicy where Id IS NOT NULL
storageAreaSearch=Select * FROM StorageArea where Id IS NOT NULL
securityPolicySearch=Select * FROM SecurityPolicy where Id IS NOT NULL
subscriptionSearch=Select * FROM Subscription where Id IS NOT NULL
sweepSearch=Select * FROM CmSweep where Id IS NOT NULL
sweepPolicySearch=Select * FROM CmSweepPolicy where Id IS NOT NULL
tableDefinitionSearch=Select * FROM TableDefinition where Id IS NOT NULL
downloadRecordSearch=Select * FROM ClbDownloadRecord where Id IS NOT NULL
summaryDataSearch=Select * FROM ClbSummaryData where Id IS NOT NULL
customRoleBaseSearch=Select * FROM CmCustomRoleBase where Id IS NOT NULL
propertyTemplateSearch=Select * FROM PropertyTemplate where Id IS NOT NULL
oneDocumentSearch=Select * FROM Document where Id={937CBAFA-9A2C-C379-87C9-93F540400000}
# oneDocumentSearch=Select * FROM Remitos
tablesCsvFile=C:\\Logs\\FnDbTables.csv
LdapUsersCsvFile=C:\\Logs\\LdapUsers.csv
LdapGroupsCsvFile=C:\\Logs\\LdapGroups.csv
PrincipalsCsvFile=C:\\Logs\\currentPrincipals.csv
PrincipalsJsonFile=C:\\Logs\\currentPrincipals.json
dbType=SQLServer
dbHost=172.16.16.113
dbPort=1433
databaseName=testing
schemaName=dbo
dbUserName=sa
dbUserPswd=Lpa23291