ceURI=https://w2019p8.lab.grupolpa.com:9443/wsi/FNCEWS40MTOM/
#ceURI=http://p8sql2012.lab.grupolpa.com:9080/wsi/FNCEWS40MTOM/
# ceURI=https://p8-55biogenesis.bago.lpa.dev:9443/wsi/FNCEWS40MTOM/
# ceURI=http://p855-cargill.lab.grupolpa.com:9080/wsi/FNCEWS40MTOM/	
userName=p85ceadmin
# userName=p8ceadmin
password=Filenet01
# password=Admin123
objectStore=OS1_FVG
# objectStore=TEST
# objectStore=objst1
# objectStore=OBJST2
#objectStore=TESTING
# objectStore=Soporte
# objectStore=ICM_T
# objectStore=ICM_D
documentSearch=Select * FROM Document where Id IS NOT NULL
folderSearch=Select * FROM Folder where Id IS NOT NULL
resultsPath=C:\\Logs\\currentPrincipals2.json