package ar.com.lpa.ldapExchanger.model;

public enum FnObjectType
{
     ANNOTATION, PROPERTY_TEMPLATE, CLASS_DEFINITION, CLASS_DEFINITION_DIP, FOLDER, DOCUMENT,
     CHOICE_LIST, CUSTOM_OBJECT, STORAGE_POLICY, STORAGE_AREA, SECURITY_POLICY, SECURITY_TEMPLATE, ROLE,
     EVENT, SWEEP, SWEEP_POLICY, TABLE_DEFINITION, ABSTRACT_PERSISTABLE, DOWNLOAD_RECORD, SUMMARY_DATA, CUSTOM_ROLE_BASE, EVENT_ACTION,
     CHANGE_PREPROCESSOR_ACTION, CLASS_SUBSCRIPTION, CONTENT_CONVERSION_ACTION, DOCUMENT_CLASSIFICATION_ACTION,
     DOCUMENT_LIFECYCLE_ACTION, DOCUMENT_LIFECYCLE_POLICY, INSTANCE_SUBSCRIPTION, ROLE_MEMBERSHIP_ACTION,
     SEARCH_FUNCTION_DEFINITION, SWEEP_ACTION, TEXT_INDEXING_PREPROCESSOR_ACTION;
}
