# This sets the global logging level and specifies the appenders
log4j.rootLogger=ALL, CONSOLE, LOGFILE

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
#log4j.appender.CONSOLE.Target=System.out

log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%C.%M:%L] - %m%n

# Filtro para que solo INFO y niveles superiores se muestren en la consola
#log4j.appender.CONSOLE.Threshold=INFO
log4j.appender.CONSOLE.Threshold=DEBUG
#log4j.appender.CONSOLE.Threshold=TRACE

log4j.appender.LOGFILE=org.apache.log4j.RollingFileAppender 
log4j.appender.LOGFILE.File=C:\\LOGS\\fnsamples.log
log4j.appender.LOGFILE.MaxFileSize=10MB 
log4j.appender.LOGFILE.MaxBackupIndex=10 
log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout 
log4j.appender.LOGFILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%C.%M:%L] - %m%n
log4j.appender.LOGFILE.append=true
log4j.appender.LOGFILE.Threshold=INFO
#log4j.appender.LOGFILE.Threshold=DEBUG

log4j.logger.org.springframework=warn
log4j.logger.org.apache.cxf=warn
log4j.logger.org.springframework.beans=warn
log4j.logger.com.filenet=warn

log4j.logger.ar.com.lpa.ldapExchanger=TRACE
log4j.logger.org.hibernate=INFO
